version: '3.8'

services:
  gateway:
    container_name: gateway
    environment:
      TASK_HOST: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: gateway
      target: development
    ports:
      - 3000:3000
    networks:
      - redis-microservices-network


  task:
    container_name: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: task
      target: development
    networks:
      - redis-microservices-network

  redis:
    container_name: redis-microservice
    image: redis
    ports:
      - "6379:6379"
    networks:
        - redis-microservices-network
    restart: always

networks:
  redis-microservices-network:
    driver: bridge
