version: '3.8'

services:
  gateway:
    container_name: gateway
    environment:
      TASK_HOST: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: gateway
      target: development
    ports:
      - 3000:3000


  task:
    container_name: task
    env_file:
      - .env
    build:

      context: .
      args:
        APP: task
      target: development
