version: '3.8'

services:
  gateway:
    container_name: gateway
    environment:
      TASK_HOST: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: gateway
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./node_modules:/app/node_modules


  task:
    container_name: task
    env_file:
      - .env
    build:

      context: .
      args:
        APP: task
      target: development
    volumes:
      - ./node_modules:/app/node_modules

  nats-broker:
    container_name: nats-broker
    entrypoint: '/nats-server -c nats-server.conf -DV'
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
