version: '3.8'

networks:
  app-net:
    driver: bridge

services:
  gateway:
    container_name: gateway
    environment:
      TASK_HOST: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: gateway
      target: development
    ports:
      - 3000:3000
    depends_on:
      - task
    networks:
      - app-net

  task:
    container_name: task
    links:
      - kafka
    env_file:
      - .env
    build:
      context: .
      args:
        APP: task
      target: development
    depends_on:
      - kafka
    networks:
      - app-net

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:3.9.2-debian-12-r3
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-net


  kafka:
    container_name: kafka
    hostname: docker.kafka.io
    image: bitnami/kafka:3.7.0-debian-12-r3
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://docker.kafka.io:9092,EXTERNAL://docker.kafka.io:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-net

