version: '3.8'

services:
  gateway:
    container_name: gateway
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - APP=gateway
    restart: always
    ports:
      - 3000:3000
  task:
    container_name: task
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - APP=task
    restart: always
    ports:
      - 3001:3000
