version: '3.8'

services:
  gateway:
    container_name: gateway
    environment:
      TASK_HOST: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: gateway
      target: development
    ports:
      - 3000:3000
    networks:
      - mqtttest


  task:
    container_name: task
    env_file:
      - .env
    build:
      context: .
      args:
        APP: task
      target: development
    networks:
      - mqtttest

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtttest
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  mqtttest:
    name: mqtttest
volumes:
  data: ~
